### ISSUE TITLE
false positive fail on "+="

### ISSUE THREAD

**Issue by iham** [gforcada/flake8-pep3101#20]
var += 1 leads to "S001 found module formatter"

wrongly, i guess.

**Comment by iham** [comment]
this was stupidity of me...

read the wrong line ...
#21 is the correct issue.

if you like, please delete this stupid issue i created falsely...

thanks :)

**Comment by gforcada** [comment]
I don't see any button to delete it, but as it is closed, let's not talk about it anymore 🙂
