### ISSUE TITLE
pep8 has been renamed to pycodestyle

### ISSUE THREAD

**Issue by alefteris** [gforcada/flake8-pep3101#4]
The pep8 package has been renamed to [pycodestyle](https://github.com/PyCQA/pycodestyle). So after installing latest flake8 (that requires pycodestyle), installing flake8-pep3101 and running flake8, I get the following error:

```
ImportError: No module named 'pep8'
```

**Comment by gforcada** [comment]
@alefteris thanks for reporting! Would you mind providing a pull request?
